version: '2'
services:
  dbpedia-spotlight:
    image: dbpedia/spotlight-french:latest
    command: java -Dfile.encoding=UTF-8 -Xmx10G -Dthreads.max=15 -Dthreads.core=15 -jar /opt/spotlight/dbpedia-spotlight-nightly-build.jar /opt/spotlight/fr  http://0.0.0.0:80/rest
    restart: always
  nlp-es-service:
    image: librairy/nlp-fr-service:latest
    restart: always
    ports:
     - "7777:7777"
     - "65111:65111"
    environment:
      - REST_PATH=/fr
